env:
  browser: true
extends: 'eslint:recommended'
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - windows
    # change the line above to unix if you are on macOS or Linux
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-console:
    - off
